note_application/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login,logout
from django.contrib.auth import views as auth_views

urlpatterns=[
    url(r'^$', views.home),
    url(r'^login/$',login,{'template_name':'accounts/login.html'}),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}),
    url(r'^register/$', views.register,name='register'),
    url(r'^profile/$', views.create_note, name='profile'),
    url(r'^notes/$', views.notes_view, name='note_view'),
    url(r'^shared_notes/$', views.shared_view, name='shared_notes'),
    url(r'^edit/(?P<pk>\d+)$', views.note_update, name='note_edit'),
    url(r'^home/$',views.home, name='home'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^delete/(?P<pk>\d+)$', views.note_delete, name='note_delete'),
]

note_application/note_application/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views as note_views


urlpatterns = [
    url(r'^$',note_views.login_redirect ,name='login_redirect'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls',namespace="accounts")),
]

note_application/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


# Create your models here.
from django.dispatch import receiver
from django.core.urlresolvers import reverse


# class UserProf(models.Model):
#     user=models.OneToOneField(User)
#     title=models.TextField(max_length=100,default=None )
#     note=models.TextField(max_length=1000,default=None)

class Noteclass(models.Model):
    user = models.ForeignKey(User)
    completed=models.BooleanField(default=False)
    shared=models.BooleanField(default=False)
    title=models.TextField(max_length=100,default=None )
    note=models.TextField(max_length=1000,default=None)

    def get_absolute_url(self):
        return reverse('accounts:note_edit', kwargs={'pk': self.pk})

# class Sharednotes(models.Model):
#     shared_to=models.ForeignKey(User,related_name='shared_to')
#     shared_by=models.ForeignKey(User,related_name='shared_by')
#     note_id=models.ForeignKey(Noteclass)




# def create_profile(sender,**kwargs):
#     if kwargs['created']:
#         user_profile=UserProf.object.create(user= kwargs['instance'])
#
# post_save.connect(create_profile, sender=User)

# @receiver(post_save, sender=User)
# def create_profile(sender, instance, created, **kwargs):
#     if created:
#         UserProf.objects.create(user=instance)

note_application/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Noteclass


class RegistrationForm(UserCreationForm):
    email=forms.EmailField(required=True)

    # def __init__(self, *args, **kwargs):
    #     super(RegistrationForm, self).__init__(*args, **kwargs)
    #     self.fields['username'].label = "username_access"
    #     self.fields['first_name'].label = "firstname_access"
    #     self.fields['last_name'].label = "lastname_access"
    #     self.fields['email'].label = "email_access"
    #     self.fields['password1'].label = "password1_access"
    #     self.fields['password2'].label = "password2_access"


    class Meta:
        model= User
        fields =(
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self,commit=True):
        user=super(RegistrationForm,self).save(commit=False)
        user.first_name= self.cleaned_data['first_name']
        user.last_name=self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        user.password1 = self.cleaned_data['password1']
        user.password2 = self.cleaned_data['password2']



        if commit:
            user.save()

        return user

class NoteForm(forms.ModelForm):



    class Meta:
        model= Noteclass
        fields =(
            'title',
            'note',
            'shared',
            'completed',
        )

    def save(self,commit=True):
        user=super(NoteForm,self).save(commit=False)
        user.title= self.cleaned_data['title']
        user.note=self.cleaned_data['note']


        if commit:
            user.save()

        return user

note_application/accounts/views.py
from account.decorators import login_required
from django.shortcuts import render, HttpResponse, redirect, render_to_response, get_object_or_404
from django.template import RequestContext
from django.views.generic import TemplateView
from django_messages.admin import User
from .models import Noteclass

from .forms import RegistrationForm,NoteForm


# Create your views here.

def home(request):
    number=[1,2,3,4]
    name="Piyush"
    args={'name':name,'number':number}
    return render(request,'accounts/home.html',args)

def register(request):
    print ("insde_reg")
    if request.method =='POST':
        print ("insde_post")
        form=RegistrationForm(request.POST)

        if form.is_valid():
            print ("insde_ifffffff")
            form.save()
            return redirect('/accounts/profile.html')
        else:

            print (form.errors ,"errrorrr") #display errors

            return render(request, 'accounts/reg_form.html', {'form': form})


    else:
        form=RegistrationForm()
        args={'form':form}

        return render(request,'accounts/reg_form.html',args)


def profile(request):
    args={'user':request.user}
    return render(request,'accounts/profile.html',args)

def notes_view(request):
    # current_user=request.user
    all_user=User.objects.all()



    # for n1 in data_shared:
    #     print (n1.title,"aaaaaaaaaaaaaaa")
    note_data= Noteclass.objects.filter(user=request.user.id)
    shared=Noteclass.objects.filter(shared=True)



    all_notes={"note_data":note_data,"all_user":all_user,"shared":shared}
    # args={'user':request.user}
    return render(request,'accounts/notes.html',all_notes)

def shared_view(request):
    all_user = User.objects.all()

    # for n1 in data_shared:
    #     print (n1.title,"aaaaaaaaaaaaaaa")
    note_data = Noteclass.objects.filter(user=request.user.id)
    shared = Noteclass.objects.filter(shared=True)



    all_notes = {"note_data": note_data, "all_user": all_user, "shared": shared}
    # args={'user':request.user}
    return render(request, 'accounts/shared_notes.html', all_notes)



@login_required
def create_note(request):
    print(request.user.id,"#########################3")
    if request.method =='POST':
        form=NoteForm(request.POST)
        form_cont = form.save(commit=False)
        # set attributes not to the form but to the model instance:
        if form.is_valid():
            # form_cont.user = User.objects.get(id=1)
            form_cont.user = request.user
            print(form_cont.user.id,"iddddd")
            form_cont.save()
            return redirect('/accounts/profile')
        else:

            return redirect('/accounts/profile')


    else:
        note_form=NoteForm()
        args={'note_form':note_form}
        # print('Entered else')

        return render(request,'accounts/profile.html',args)

@login_required
def note_update(request, pk, template_name='accounts/edit.html'):
    if request.user.is_superuser:
        note= get_object_or_404(Noteclass, pk=pk)
    else:
        note= get_object_or_404(Noteclass, pk=pk, user=request.user)
    form = NoteForm(request.POST or None, instance=note)
    if form.is_valid():

        form.save()

        return redirect('accounts:note_view')
    return render(request, template_name, {'form':form})



@login_required
def note_delete(request, pk, template_name='accounts/note_confirm_delete.html'):
    if request.user.is_superuser:
        note= get_object_or_404(Noteclass, pk=pk)
    else:
        note= get_object_or_404(Noteclass, pk=pk, user=request.user)
    if request.method=='POST':
        note.delete()
        return redirect('accounts:note_view')
    return render(request, template_name, {'object':note})

note_application/note_application/views.py
from django.shortcuts import redirect

def login_redirect(request):
    return redirect('accounts/login')

note_application/accounts/templates/accounts/edit.html
{% extends 'base.html' %}











<DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head %}
    <title>Profile</title>
    {% endblock %}
</head>
<body>
        {% block body %}


<div class="container">
  <div class="jumbotron" style="text-align: center;">
    <h1 >Welcome {{ user.first_name }} {{ user.last_name }}</h1>
    <p>Edit new notes in this section.</p>
  </div>
</div>








<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="robots" content="noindex, nofollow">

    <title>Simple Contact Form - Bootsnipp.com</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <style type="text/css">
.hsonuc {
    position: absolute;
    top: 100px;
    margin:auto;
    margin-left:200px;

}
.red{
    color:red;
    }
.form-area
{
    background-color: #FAFAFA;
	padding: 10px 40px 60px;
	margin: 10px 0px 60px;
	border: 1px solid GREY;

	}
    </style>

</head>
<body>
	<div class="container" >
                <div class="row">
<div class="col-md-5" >
    <div class="form-area">
        <form role="form" method="post" >
            {% csrf_token %}
        <br style="clear:both">
                    <h3 style="margin-bottom: 25px; text-align: center;">Edit note</h3>

					<div class="form-group">
                        <textarea rows="4" cols="50"  class="form-control"  name="title"  value="{{form.title}} "> </textarea>
					 <!--<label for="id_title"></label>-->
                    </div>
                    <div class="form-group">
                        <!--<label for="id_note"></label>-->
                    <textarea rows="4" cols="50" class="form-control"   name="note"  maxlength="140" rows="7" value="{{ form.note }}" ></textarea>



                        {% if form.shared %}
                        <input type="checkbox" name="shared" checked value="{{ form.shared }}" /> Share
                        {% else %}
                        <input type="checkbox" name="shared"  value="{{form.shared}}" /> Share
                        {% endif %}
                        {% if form.completed %}
                        <input type="checkbox" name="completed" checked value="{{ form.completed }}"/> Completed
                        {% else %}
                         <input type="checkbox" name="completed" value="{{ form.completed }}"/> Completed
                        {% endif %}

                    </div>

        <button type="submit"   class="btn btn-success pull-right">Edit Note</button>
        </form>
    </div>
    </div>
                    <div class="col-md-5"  >
                        <div class="hsonuc">
                            <h3 >Jumb to View Notes</h3>
                            <div>
                        <small class="text-muted">View your own notes</small>

                      <div ><a style="margin: 5px 0px 16px;" href="/accounts/notes" class="btn btn-price btn-success btn-lg">Your Notes</a></div>
                       <small class="text-muted">View shared notes</small>
                            <div ><a style="margin: 10px 0px 60px;"  href="/accounts/shared_notes" class="btn btn-price btn-success btn-lg">Shared</a></div>
                    </div>
                            </div>
                    </div>

</div>
</div>

</body>
</html>


    {% endblock %}

</body>
</html>

note_application/accounts/templates/accounts/home.html
{% extends 'base.html' %}
<DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head %}
    <title>home</title>
    {% endblock %}
</head>
<body>
        {% block body %}
      <h1>Hey home here</h1>
        {% endblock %}

</body>
</html>

note_application/accounts/templates/accounts/login.html
{% extends 'base.html' %}
<DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>Log out</title>

<!--{% load static %}-->
    <!--<link rel="stylesheet" href="{% static 'accounts/style.css' %}" type="text/css">-->
    {% endblock %}
</head>
<body background="black">{% block body %}








<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="robots" content="noindex, nofollow">

    <title>login</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <style type="text/css">

/*
    Note: It is best to use a less version of this file ( see http://css2less.cc
    For the media queries use @screen-sm-min instead of 768px.
    For .omb_spanOr use @body-bg instead of white.
*/

@media (min-width: 768px) {
    .omb_row-sm-offset-3 div:first-child[class*="col-"] {
        margin-left: 25%;

    }
}

.omb_login .omb_authTitle {
    text-align: center;
	line-height: 300%;
}

.omb_login .omb_socialButtons a {
	color: white; // In yourUse @body-bg
	opacity:0.9;
}
.omb_login .omb_socialButtons a:hover {
    color: white;
	opacity:1;
}
.omb_login .omb_socialButtons .omb_btn-facebook {background: #3b5998;}
.omb_login .omb_socialButtons .omb_btn-twitter {background: #00aced;}
.omb_login .omb_socialButtons .omb_btn-google {background: #c32f10;}


.omb_login .omb_loginOr {
	position: relative;
	font-size: 1.5em;
	color: #aaa;
	margin-top: 1em;
	margin-bottom: 1em;
	padding-top: 0.5em;
	padding-bottom: 0.5em;
}
.omb_login .omb_loginOr .omb_hrOr {
	background-color: #cdcdcd;
	height: 1px;
	margin-top: 0px !important;
	margin-bottom: 0px !important;
}
.omb_login .omb_loginOr .omb_spanOr {
	display: block;
	position: absolute;
	left: 50%;
	top: -0.6em;
	margin-left: -1.5em;
	background-color: white;
	width: 3em;
	text-align: center;
}

.omb_login .omb_loginForm .input-group.i {
	width: 2em;
}
.omb_login .omb_loginForm  .help-block {
    color: red;
}


@media (min-width: 768px) {
    .omb_login .omb_forgotPwd {
        text-align: right;
		margin-top:10px;

 	}
}
    </style>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        window.alert = function(){};
        var defaultCSS = document.getElementById('bootstrap-css');
        function changeCSS(css){
            if(css) $('head > link').filter(':first').replaceWith('<link rel="stylesheet" href="'+ css +'" type="text/css" />');
            else $('head > link').filter(':first').replaceWith(defaultCSS);
        }
        $( document ).ready(function() {
          var iframe_height = parseInt($('html').height());
          window.parent.postMessage( iframe_height, 'https://bootsnipp.com');
        });
    </script>
</head>
<body>
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

<div class="container"   >


    <div class="omb_login">
    	<h3 class="omb_authTitle">Login or <a href="/accounts/register">Sign up</a></h3>


		<div class="row omb_row-sm-offset-3 omb_loginOr">
			<div class="col-xs-12 col-sm-6">
				<hr class="omb_hrOr">
				<span class="omb_spanOr"></span>
			</div>
		</div>

		<div class="row omb_row-sm-offset-3">
			<div class="col-xs-12 col-sm-6">
			    <form class="omb_loginForm" action="" autocomplete="off" method="POST"  action="{% url 'accounts:login' %} ">
                    {% csrf_token %}
					<div class="input-group" >
						<span class="input-group-addon"><i class="fa fa-user"></i></span>
                    <label for="id_username"></label>
						<input type="utext" class="form-control" name="username" placeholder="Username" >
            </div>
					<span class="help-block"></span>

					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-lock"></i></span>
                        <label for="id_password"></label>
						<input  type="password" class="form-control" name="password" placeholder="Password">
					</div>
                    <span class="help-block"></span>

                    <div style="text-align: left; margin-top: 15px; margin-bottom: 18px;"> {% if form.errors %}
                    <p class=" label label-danger">
                        Your username and password didn't match.Please try again.</p>

                {% endif %}
                    </div>

					<button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
				</form>
			</div>
    	</div>
		<div class="row omb_row-sm-offset-3">
			<div class="col-xs-12 col-sm-3">
				<label class="checkbox">
					<!--<input type="checkbox" value="remember-me">-->
				</label>
			</div>
			<div class="col-xs-12 col-sm-3">
				<p class="omb_forgotPwd">
					<a href="#"></a>
				</p>
			</div>
		</div>
	</div>



        </div>
	<script type="text/javascript">

	</script>
</body>
</html>

 {% endblock %}
</body>
</html>

note_application/accounts/templates/accounts/logout.html
{% extends 'base.html' %}

<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>Welcome</title>
    <style>
h3 {
    text-align: center;
}
    </style>

<!--{% load static %}-->
    <!--<link rel="stylesheet" href="{% static 'accounts/style.css' %}" type="text/css">-->
    {% endblock %}
</head>
<body >
{% block body %}
<br><br><br>


    <h3>You have logged out</h3>




     {% endblock %}

</body>
</html>

note_application/accounts/templates/accounts/note_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

note_application/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
<DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head %}
    <title>Profile</title>
    {% endblock %}
</head>
<body>
        {% block body %}


<div class="container">
  <div class="jumbotron" style="text-align: center;">
    <h1 >Welcome {{ user.first_name }} {{ user.last_name }}</h1>
    <p>Create new notes in this section.</p>
  </div>
</div>








<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="robots" content="noindex, nofollow">

    <title>Simple Contact Form - Bootsnipp.com</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <style type="text/css">
.hsonuc {
    position: absolute;
    top: 100px;
    margin:auto;
    margin-left:200px;

}
.red{
    color:red;
    }
.form-area
{
    background-color: #FAFAFA;
	padding: 10px 40px 60px;
	margin: 10px 0px 60px;
	border: 1px solid GREY;

	}
    </style>

</head>
<body>
	<div class="container" >
                <div class="row">
<div class="col-md-5" >
    <div class="form-area">
        <form role="form" method="post" action="{% url 'accounts:profile' %} ">
            {% csrf_token %}
        <br style="clear:both">
                    <h3 style="margin-bottom: 25px; text-align: center;">Create new note</h3>

					<div class="form-group">
						<input type="text" class="form-control"  name="title" placeholder="Title" required>
					 <label for="id_title"></label>
                    </div>
                    <div class="form-group">
                        <label for="id_note"></label>
                    <textarea class="form-control" type="textarea"  name="note" placeholder="Message" maxlength="140" rows="7"></textarea>


                    </div>

        <button type="submit"   class="btn btn-success pull-right">Create Note</button>
        </form>
    </div>
    </div>
                    <div class="col-md-5"  >
                        <div class="hsonuc">
                            <h3 >Jumb to View Notes</h3>
                            <div>
                        <small class="text-muted">View your own notes</small>

                      <div ><a style="margin: 5px 0px 16px;" href="/accounts/notes" class="btn btn-price btn-success btn-lg">Your Notes</a></div>
                       <small class="text-muted">View shared notes</small>
                            <div ><a style="margin: 10px 0px 60px;"  href="/accounts/shared_notes" class="btn btn-price btn-success btn-lg">Shared</a></div>
                    </div>
                            </div>
                    </div>

</div>
</div>

</body>
</html>


    {% endblock %}

</body>
</html>

note_application/accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
<h1></h1>








<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="robots" content="noindex, nofollow">

    <title>Responsive login with social buttons - Bootsnipp.com</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <style type="text/css">

/*
    Note: It is best to use a less version of this file ( see http://css2less.cc
    For the media queries use @screen-sm-min instead of 768px.
    For .omb_spanOr use @body-bg instead of white.
*/

@media (min-width: 768px) {
    .omb_row-sm-offset-3 div:first-child[class*="col-"] {
        margin-left: 25%;
    }
}

.omb_login .omb_authTitle {
    text-align: center;
	line-height: 300%;
}

.omb_login .omb_socialButtons a {
	color: white; // In yourUse @body-bg
	opacity:0.9;
}
.omb_login .omb_socialButtons a:hover {
    color: white;
	opacity:1;
}
.omb_login .omb_socialButtons .omb_btn-facebook {background: #3b5998;}
.omb_login .omb_socialButtons .omb_btn-twitter {background: #00aced;}
.omb_login .omb_socialButtons .omb_btn-google {background: #c32f10;}


.omb_login .omb_loginOr {
	position: relative;
	font-size: 1.5em;
	color: #aaa;
	margin-top: 1em;
	margin-bottom: 1em;
	padding-top: 0.5em;
	padding-bottom: 0.5em;
}
.omb_login .omb_loginOr .omb_hrOr {
	background-color: #cdcdcd;
	height: 1px;
	margin-top: 0px !important;
	margin-bottom: 0px !important;
}
.omb_login .omb_loginOr .omb_spanOr {
	display: block;
	position: absolute;
	left: 50%;
	top: -0.6em;
	margin-left: -1.5em;
	background-color: white;
	width: 3em;
	text-align: center;
}

.omb_login .omb_loginForm .input-group.i {
	width: 2em;
}
.omb_login .omb_loginForm  .help-block {
    color: red;
}


@media (min-width: 768px) {
    .omb_login .omb_forgotPwd {
        text-align: right;
		margin-top:10px;
 	}
}
    </style>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        window.alert = function(){};
        var defaultCSS = document.getElementById('bootstrap-css');
        function changeCSS(css){
            if(css) $('head > link').filter(':first').replaceWith('<link rel="stylesheet" href="'+ css +'" type="text/css" />');
            else $('head > link').filter(':first').replaceWith(defaultCSS);
        }
        $( document ).ready(function() {
          var iframe_height = parseInt($('html').height());
          window.parent.postMessage( iframe_height, 'https://bootsnipp.com');
        });
    </script>
</head>
<body>
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

<div class="container">


    <div class="omb_login">
    	<h3 class="omb_authTitle"> <a href="#">Sign Up</a></h3>


		<div class="row omb_row-sm-offset-3 omb_loginOr">
			<div class="col-xs-12 col-sm-6">
				<hr class="omb_hrOr">
				<span class="omb_spanOr"></span>
			</div>
		</div>

		<div class="row omb_row-sm-offset-3">
			<div class="col-xs-12 col-sm-6">
			    <form class="omb_loginForm"  autocomplete="off" method="POST" action="{% url 'accounts:register' %}"  >
                    {% csrf_token %}

					<div class="input-group" style=" margin-top: 10px; margin-bottom: 15px;">
						<span class="input-group-addon"><i class="fa fa-user"></i></span>
                    <label for="id_username"></label>
						<input type="utext" class="form-control" name="username" placeholder="Username" >
                    </div>
                    <div class="input-group"  style=" margin-top: 10px; margin-bottom: 15px;">
						<span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                    <label for="id_email"></label>
						<input type="utext" class="form-control" name="email" placeholder="Email-Id" >
                    </div>
					<div class="input-group" style=" margin-top: 10px; margin-bottom: 15px;">
						<span class="input-group-addon"><i class="fa fa-copy"></i></span>
                    <label for="id_first_name"></label>
						<input type="utext" class="form-control" name="first_name" placeholder="First Name" >

                        <span class="input-group-addon"><i class="fa fa-copy"></i></span>
                    <label for="id_last_name"></label>
						<input type="utext" class="form-control" name="last_name" placeholder="Last Name" >

                    </div>



                    <div class="input-group" style=" margin-top: 10px; margin-bottom: 15px;">
						<span class="input-group-addon"><i class="fa fa-lock"></i></span>
                    <label for="id_password1"></label>
						<input type="password" class="form-control" name="password1" placeholder="Password" >

                        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                    <label for="id_password2"></label>
						<input type="password" class="form-control"  name="password2" placeholder="Confirm Password" >
                    </div>







                    <div style="text-align: left; margin-top: 15px; margin-bottom: 18px;">


                    <p class=" label label-danger">{% if form.errors.username %}
                        Invalid username.Please try again.
						{% elif form.errors.password1 %}
						  Invalid password1.Please try again.
						{% elif form.errors.password2 %}
						  Invalid password2.Please try again.
						{% elif form.errors.email %}
						  Invalid email.Please try again.
						{% endif %}</p>
					</div>

					<button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
				</form>
			</div>
    	</div>
		<div class="row omb_row-sm-offset-3">
			<div class="col-xs-12 col-sm-3">
				<!--<label class="checkbox">-->
					<!--<input type="checkbox" value="remember-me">Remember Me-->
				<!--</label>-->
			</div>
			<div class="col-xs-12 col-sm-3">
				<p class="omb_forgotPwd">
					<a href="#"></a>
				</p>
			</div>
		</div>
	</div>



        </div>
	<script type="text/javascript">

	</script>
</body>
</html>

 {% endblock %}
</body>
</html>